name: merkle-schemes-higher
version: 0.1.0.0
synopsis: merkle all the things
github: pkinsky/merkle-schemes
author: Paul Kinsky
category: Development

ghc-options: -Wall -Werror

default-extensions:
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - KindSignatures
  - OverloadedStrings
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeOperators


dependencies:
  - base >=4.8
  - aeson
  - base16-bytestring
  - base64-bytestring
  - bifunctors
  - bytestring
  - containers
  - directory
  - deriving-compat
  - free
  - memory
  - mtl
  - unordered-containers
  - pretty
  - random
  - safe-exceptions
  - singletons
  - text
  - transformers


library:
  source-dirs: src
  exposed-modules:
    - Merkle.Higher.Store
    - Merkle.Higher.Store.Deref
    - Merkle.Higher.Types
    - Util.HRecursionSchemes
