name: merkle-schemes
version: 0.1.0.0
synopsis: merkle all the things
github: pkinsky/merkle-schemes
author: Paul Kinsky
category: Development

ghc-options: -Wall -Werror

default-extensions:
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - KindSignatures
  - OverloadedStrings
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeOperators


dependencies:
  - base >=4.8
  - aeson
  - aeson-pretty
  - base16-bytestring
  - base64-bytestring
  - bifunctors
  - bytestring
  - containers
  - cryptonite
  - directory
  - deriving-compat
  - free
  - http-client
  - memory
  - mtl
  - unordered-containers
  - pretty
  - optparse-applicative
  - random
  - recursion-schemes
  - safe-exceptions
  - servant
  - servant-client
  - servant-server
  - singletons
  - text
  - transformers
  - vector
  - warp
  - wreq
  - lens-aeson
  - lens

library:
  source-dirs: src
  exposed-modules:
    - Data.Aeson.Orphans
    - Merkle.Functors
    - Merkle.Store
    - Merkle.Store.Deref
    - Merkle.Store.FileSystem
    - Merkle.Store.InMemory
    - Merkle.Store.Network
    - Merkle.Types
    - Util.RecursionSchemes

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hedgehog
      - hspec
      - hw-hspec-hedgehog
      - merkle-schemes
      - temporary
    build-tools: hspec-discover
